language: android
jdk:
- oraclejdk7

env:
  global:
    secure: OTmx8EZyUxB3LHYw9o8XaWmYo4UiZKIG97bgGMXEjkuXDnszcq6hy3o4q+tTbelkdv9NnEbRoIJ3pt2rG4QXPEXCCJkjN7nUq+JvmBXLylwAo5ngyqPqbYGYh7p4eyy473xDh/eLk/hk/WVg8SVS2FcKt3XSqOc66cazGgSBJSM=

android:
  components:
    - platform-tools
    - tools
  licenses:
    - 'android-sdk-license-.+'

before_script:
    - echo yes | android update sdk -u -a -t tools
    - echo yes | android update sdk -u -a -t build-tools-21.1.2
    - echo yes | android update sdk -u -a -t android-21
    - echo yes | android update sdk -u -a -t extra-google-m2repository
    - echo yes | android update sdk -u -a -t extra-android-m2repository
    - echo yes | android update sdk -u -a -t extra-android-support,extra-google-google_play_services

script: ./gradlew clean lintDebug test assembleDebug
after_success:
- chmod a+x .utility/push-docs-to-gh-pages.sh
- .utility/push-docs-to-gh-pages.sh
- curl -H "X-CI-Build: $DK_CI_Key" http://dronekit.io/ci?build=android&branch=master
